const navToggle=document.querySelector('.nav-toggle');
const mainNav=document.querySelector('#main-nav');
navToggle?.addEventListener('click',()=>{const open=mainNav?.classList.toggle('open')??false;navToggle.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>{mainNav?.classList.remove('open');navToggle?.setAttribute('aria-expanded','false');}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target);}}),{threshold:.12});
document.querySelectorAll('.reveal:not(.is-visible)').forEach(el=>revealObserver.observe(el));
const sections=[...document.querySelectorAll('main section[id]')];const links=[...document.querySelectorAll('.main-nav a')];
const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`));}),{rootMargin:'-40% 0px -55% 0px'});
sections.forEach(s=>navObserver.observe(s));
const toTop=document.querySelector('#to-top');window.addEventListener('scroll',()=>toTop?.classList.toggle('show',window.scrollY>500),{passive:true});toTop?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.closest('figure')?.classList.add('image-fallback');}));
const quizData=[
{q:'Đoàn Khuê tham gia phong trào Thanh niên phản đế phủ Triệu Phong khi bao nhiêu tuổi?',o:['15 tuổi','16 tuổi','18 tuổi'],a:1,x:'Năm 1939, ông tham gia phong trào khi mới 16 tuổi.'},
{q:'Ngày 30/10/1940, Đoàn Khuê bị bắt và sau đó bị đưa đi đâu?',o:['Lao Bảo','Buôn Ma Thuột','Vĩnh Linh'],a:1,x:'Ông bị kết án tù ở nhà lao Quảng Trị rồi bị đưa đi đày ở Buôn Ma Thuột.'},
{q:'Đoàn Khuê ra tù vào thời điểm nào?',o:['Tháng 5/1945','Tháng 8/1945','Cuối năm 1945'],a:0,x:'Tháng 5/1945, ông ra tù và về Quảng Bình hoạt động gây dựng cơ sở cách mạng.'},
{q:'Trong giai đoạn 1948–1954, ông giữ cương vị nào ở Trung đoàn 108?',o:['Chính ủy, Bí thư Trung đoàn ủy','Phó Chính ủy Quân khu 4','Tư lệnh Quân khu 5'],a:0,x:'Ông là Chính ủy, Bí thư Trung đoàn ủy Trung đoàn 108.'},
{q:'Từ 1963 đến 1975, Đoàn Khuê được điều động vào chiến trường nào?',o:['Khu 4','Khu 5','Khu 6'],a:1,x:'Ông được điều động vào chiến trường Khu 5, giữ chức Phó Chính ủy Quân khu 5.'}
];
let qi=0,score=0,selected=null,answered=false;const box=document.querySelector('#quiz-box'),prog=document.querySelector('#quiz-progress'),next=document.querySelector('#quiz-next'),restart=document.querySelector('#quiz-restart'),result=document.querySelector('#quiz-result');
function renderQuestion(){if(!box||!prog||!next)return;const item=quizData[qi];selected=null;answered=false;prog.textContent=`${String(qi+1).padStart(2,'0')} / ${quizData.length}`;next.textContent=qi===quizData.length-1?'Chấm điểm':'Câu tiếp theo →';next.classList.remove('hidden');restart?.classList.add('hidden');result?.classList.add('hidden');box.innerHTML=`<div class="quiz-question"><h3>${item.q}</h3><div class="quiz-options" role="radiogroup">${item.o.map((opt,i)=>`<button class="quiz-option" type="button" data-index="${i}" aria-pressed="false"><span class="quiz-marker">${String.fromCharCode(65+i)}</span><span>${opt}</span></button>`).join('')}</div></div>`;box.querySelectorAll('.quiz-option').forEach(btn=>btn.addEventListener('click',()=>{if(answered)return;box.querySelectorAll('.quiz-option').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});btn.classList.add('selected');btn.setAttribute('aria-pressed','true');selected=Number(btn.dataset.index);}));}
next?.addEventListener('click',()=>{if(answered){if(qi<quizData.length-1){qi++;renderQuestion();}return;}if(selected===null){next.animate([{transform:'translateX(0)'},{transform:'translateX(-5px)'},{transform:'translateX(5px)'},{transform:'translateX(0)'}],{duration:240});return;}const item=quizData[qi],ok=selected===item.a;if(ok)score++;answered=true;box.querySelectorAll('.quiz-option').forEach((btn,i)=>{btn.disabled=true;if(i===item.a)btn.classList.add('correct');if(i===selected&&!ok)btn.classList.add('wrong');});const exp=document.createElement('div');exp.className='quiz-explanation';exp.innerHTML=`<strong>${ok?'Đúng.':'Chưa đúng.'}</strong> ${item.x}`;box.querySelector('.quiz-question')?.appendChild(exp);if(qi===quizData.length-1){const pct=Math.round(score/quizData.length*100);prog.textContent='HOÀN TẤT';if(result){result.classList.remove('hidden');result.innerHTML=`<strong>${score} / ${quizData.length} câu đúng</strong> · ${pct}%`;}next.classList.add('hidden');restart?.classList.remove('hidden');}else next.textContent='Câu tiếp theo →';});
restart?.addEventListener('click',()=>{qi=0;score=0;renderQuestion();});renderQuestion();